package ttu.idu0080.order.teenus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T19:02:28.046+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://teenus.order.idu0080.ttu/", name = "CourierTeenus")
@XmlSeeAlso({ttu.idu0080.order.server.ObjectFactory.class, ObjectFactory.class})
public interface CourierTeenus {

    @WebMethod
    @RequestWrapper(localName = "getCourierById", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierById")
    @ResponseWrapper(localName = "getCourierByIdResponse", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ttu.idu0080.order.server.Courier getCourierById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getCourierList", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierList")
    @ResponseWrapper(localName = "getCourierListResponse", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.order.server.Courier> getCourierList();
}
