
package ttu.idu0080.order.teenus;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import ttu.idu0080.order.server.Courier;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T19:02:27.979+03:00
 * Generated source version: 3.1.10
 * 
 */
public final class CourierTeenus_OrderTeenusPort_Client {

    private static final QName SERVICE_NAME = new QName("http://teenus.order.idu0080.ttu/", "OrderTeenusService");

    public CourierTeenus_OrderTeenusPort_Client() {
    }
    
    public java.util.List<Courier> getCouriers() throws Exception {
    	URL wsdlURL = OrderTeenusService.WSDL_LOCATION;
    	String args[]={""};
    	java.util.List<ttu.idu0080.order.server.Courier> _getAllCouriers__return = null;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    //wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderTeenusService ss = new OrderTeenusService(wsdlURL, SERVICE_NAME);
        CourierTeenus port = ss.getOrderTeenusPort();  
        
        {
    	System.out.println("Invoking getAllCouriers...");
    	_getAllCouriers__return = port.getCourierList();
        }
        return _getAllCouriers__return;
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrderTeenusService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        OrderTeenusService ss = new OrderTeenusService(wsdlURL, SERVICE_NAME);
        CourierTeenus port = ss.getOrderTeenusPort();  
        
        {
        System.out.println("Invoking getCourierById...");
        int _getCourierById_arg0 = -239986300;
        ttu.idu0080.order.server.Courier _getCourierById__return = port.getCourierById(_getCourierById_arg0);
        System.out.println("getCourierById.result=" + _getCourierById__return);


        }
        {
        System.out.println("Invoking getCourierList...");
        java.util.List<ttu.idu0080.order.server.Courier> _getCourierList__return = port.getCourierList();
        System.out.println("getCourierList.result=" + _getCourierList__return);


        }

        System.exit(0);
    }

}
