
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.teenus;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T21:14:11.553+03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderTeenusService",
                      portName = "OrderTeenusPort",
                      targetNamespace = "http://teenus.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/OrderTeenus/services/OrderTeenusPort?wsdl",
                      endpointInterface = "ttu.idu0080.order.teenus.Teenus")
                      
public class OrderTeenusImpl implements Teenus {

    private static final Logger LOG = Logger.getLogger(OrderTeenusImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#getCourierById(int arg0)*
     */
    public ttu.idu0080.order.server.Courier getCourierById(int arg0) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(arg0);
        try {
            ttu.idu0080.order.server.Courier _return = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnAddressesVal1.setAddress(-711289372);
            _returnAddressesVal1.setCountry("Country-798945212");
            _returnAddressesVal1.setCounty("County1757713678");
            _returnAddressesVal1.setStreetAddress("StreetAddress38715836");
            _returnAddressesVal1.setTownVillage("TownVillage-1674325823");
            _returnAddressesVal1.setZipcode("Zipcode-2009851652");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(-2062786503);
            _return.setName("Name1289029474");
            _return.setPercentFromOrder(-659798342);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#getCourierList()*
     */
    public java.util.List<ttu.idu0080.order.server.Courier> getCourierList() { 
        LOG.info("Executing operation getCourierList");
        try {
            java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
            ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnVal1AddressesVal1.setAddress(79275558);
            _returnVal1AddressesVal1.setCountry("Country496973964");
            _returnVal1AddressesVal1.setCounty("County1213884203");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress1295523942");
            _returnVal1AddressesVal1.setTownVillage("TownVillage1906595236");
            _returnVal1AddressesVal1.setZipcode("Zipcode-1836374307");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(-342229646);
            _returnVal1.setName("Name2112941202");
            _returnVal1.setPercentFromOrder(127397472);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#getOffer(int arg0, ttu.idu0080.order.server.Order arg1)*
     */
    public ttu.idu0080.order.teenus.Pakkumine getOffer(int arg0, ttu.idu0080.order.server.Order arg1) { 
        LOG.info("Executing operation getOffer");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            ttu.idu0080.order.teenus.Pakkumine _return = new ttu.idu0080.order.teenus.Pakkumine();
            _return.setDeliveryTime(-290764498);
            _return.setOfferId("OfferId-1356138329");
            _return.setPrice(0.9388659f);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
