
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.teenus;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T23:03:07.445+03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderTeenusService",
                      portName = "OrderTeenusPort",
                      targetNamespace = "http://teenus.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/OrderTeenus/services/OrderTeenusPort?wsdl",
                      endpointInterface = "ttu.idu0080.order.teenus.Teenus")
                      
public class OrderTeenusImpl implements Teenus {

    private static final Logger LOG = Logger.getLogger(OrderTeenusImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#getCourierById(int arg0)*
     */
    public ttu.idu0080.order.server.Courier getCourierById(int arg0) { 
        LOG.info("Executing operation getCourierById");
        System.out.println(arg0);
        try {
            ttu.idu0080.order.server.Courier _return = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnAddressesVal1.setAddress(797991865);
            _returnAddressesVal1.setCountry("Country293590727");
            _returnAddressesVal1.setCounty("County1204578874");
            _returnAddressesVal1.setStreetAddress("StreetAddress340529634");
            _returnAddressesVal1.setTownVillage("TownVillage-285916805");
            _returnAddressesVal1.setZipcode("Zipcode-1108422698");
            _returnAddresses.add(_returnAddressesVal1);
            _return.getAddresses().addAll(_returnAddresses);
            _return.setEnterprise(-429651207);
            _return.setName("Name1533108544");
            _return.setPercentFromOrder(-38404346);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#getCourierList()*
     */
    public java.util.List<ttu.idu0080.order.server.Courier> getCourierList() { 
        LOG.info("Executing operation getCourierList");
        try {
            java.util.List<ttu.idu0080.order.server.Courier> _return = new java.util.ArrayList<ttu.idu0080.order.server.Courier>();
            ttu.idu0080.order.server.Courier _returnVal1 = new ttu.idu0080.order.server.Courier();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1Addresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnVal1AddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnVal1AddressesVal1.setAddress(-1815480842);
            _returnVal1AddressesVal1.setCountry("Country-1038501992");
            _returnVal1AddressesVal1.setCounty("County-604507104");
            _returnVal1AddressesVal1.setStreetAddress("StreetAddress-1027958586");
            _returnVal1AddressesVal1.setTownVillage("TownVillage-962148657");
            _returnVal1AddressesVal1.setZipcode("Zipcode915394005");
            _returnVal1Addresses.add(_returnVal1AddressesVal1);
            _returnVal1.getAddresses().addAll(_returnVal1Addresses);
            _returnVal1.setEnterprise(-2077071568);
            _returnVal1.setName("Name-1380949306");
            _returnVal1.setPercentFromOrder(2040249291);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#generateTrackingNumber(java.lang.String arg0)*
     */
    public java.lang.String generateTrackingNumber(java.lang.String arg0) { 
        LOG.info("Executing operation generateTrackingNumber");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-2009229881";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.teenus.Teenus#getOffer(int arg0, ttu.idu0080.order.server.Order arg1)*
     */
    public ttu.idu0080.order.teenus.Pakkumine getOffer(int arg0, ttu.idu0080.order.server.Order arg1) { 
        LOG.info("Executing operation getOffer");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            ttu.idu0080.order.teenus.Pakkumine _return = new ttu.idu0080.order.teenus.Pakkumine();
            _return.setDeliveryTime(487070581);
            _return.setOfferId("OfferId167272696");
            _return.setPrice(0.9669092f);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
