package ttu.idu0080.order.teenus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T23:03:07.460+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://teenus.order.idu0080.ttu/", name = "Teenus")
@XmlSeeAlso({ttu.idu0080.order.server.ObjectFactory.class, ObjectFactory.class})
public interface Teenus {

    @WebMethod
    @RequestWrapper(localName = "getCourierById", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierById")
    @ResponseWrapper(localName = "getCourierByIdResponse", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ttu.idu0080.order.server.Courier getCourierById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getCourierList", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierList")
    @ResponseWrapper(localName = "getCourierListResponse", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetCourierListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.order.server.Courier> getCourierList();

    @WebMethod
    @RequestWrapper(localName = "generateTrackingNumber", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GenerateTrackingNumber")
    @ResponseWrapper(localName = "generateTrackingNumberResponse", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GenerateTrackingNumberResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String generateTrackingNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getOffer", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetOffer")
    @ResponseWrapper(localName = "getOfferResponse", targetNamespace = "http://teenus.order.idu0080.ttu/", className = "ttu.idu0080.order.teenus.GetOfferResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ttu.idu0080.order.teenus.Pakkumine getOffer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        ttu.idu0080.order.server.Order arg1
    );
}
