
package ttu.idu0080.order.teenus.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.9
 * Mon May 22 22:52:06 EEST 2017
 * Generated source version: 3.1.9
 */

@XmlRootElement(name = "generateTrackingNumber", namespace = "http://teenus.order.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generateTrackingNumber", namespace = "http://teenus.order.idu0080.ttu/")

public class GenerateTrackingNumber {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

