
package ttu.idu0080.order.teenus.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.9
 * Mon May 22 22:52:06 EEST 2017
 * Generated source version: 3.1.9
 */

@XmlRootElement(name = "generateTrackingNumberResponse", namespace = "http://teenus.order.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "generateTrackingNumberResponse", namespace = "http://teenus.order.idu0080.ttu/")

public class GenerateTrackingNumberResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

