
package ttu.idu0080.order.teenus.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.9
 * Thu May 18 12:32:23 EEST 2017
 * Generated source version: 3.1.9
 */

@XmlRootElement(name = "getCourierListResponse", namespace = "http://teenus.order.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getCourierListResponse", namespace = "http://teenus.order.idu0080.ttu/")

public class GetCourierListResponse {

    @XmlElement(name = "return")
    private java.util.List<ttu.idu0080.order.server.Courier> _return;

    public java.util.List<ttu.idu0080.order.server.Courier> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<ttu.idu0080.order.server.Courier> new_return)  {
        this._return = new_return;
    }

}

