
package ttu.idu0080.order.teenus.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.9
 * Mon May 22 22:30:28 EEST 2017
 * Generated source version: 3.1.9
 */

@XmlRootElement(name = "getOffer", namespace = "http://teenus.order.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOffer", namespace = "http://teenus.order.idu0080.ttu/", propOrder = {"arg0", "arg1"})

public class GetOffer {

    @XmlElement(name = "arg0")
    private int arg0;
    @XmlElement(name = "arg1")
    private ttu.idu0080.order.server.Order arg1;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

    public ttu.idu0080.order.server.Order getArg1() {
        return this.arg1;
    }

    public void setArg1(ttu.idu0080.order.server.Order newArg1)  {
        this.arg1 = newArg1;
    }

}

