
package ttu.idu0080.order.teenus.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.9
 * Mon May 22 22:30:28 EEST 2017
 * Generated source version: 3.1.9
 */

@XmlRootElement(name = "getOfferResponse", namespace = "http://teenus.order.idu0080.ttu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getOfferResponse", namespace = "http://teenus.order.idu0080.ttu/")

public class GetOfferResponse {

    @XmlElement(name = "return")
    private ttu.idu0080.order.offer.Pakkumine _return;

    public ttu.idu0080.order.offer.Pakkumine getReturn() {
        return this._return;
    }

    public void setReturn(ttu.idu0080.order.offer.Pakkumine new_return)  {
        this._return = new_return;
    }

}

