package ttu.idu0080.order.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-15T23:54:27.217+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "CourierServiceService", 
                  wsdlLocation = "file:/C:/Users/Tony Bigwell/workspace/ProductServer/WebContent/couriers_1.wsdl",
                  targetNamespace = "http://server.order.idu0080.ttu/") 
public class CourierServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.order.idu0080.ttu/", "CourierServiceService");
    public final static QName CourierServicePort = new QName("http://server.order.idu0080.ttu/", "CourierServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Tony Bigwell/workspace/ProductServer/WebContent/couriers_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CourierServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Tony Bigwell/workspace/ProductServer/WebContent/couriers_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CourierServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CourierServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CourierServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CourierServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CourierServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CourierServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CourierService
     */
    @WebEndpoint(name = "CourierServicePort")
    public CourierService getCourierServicePort() {
        return super.getPort(CourierServicePort, CourierService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CourierService
     */
    @WebEndpoint(name = "CourierServicePort")
    public CourierService getCourierServicePort(WebServiceFeature... features) {
        return super.getPort(CourierServicePort, CourierService.class, features);
    }

}
