
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10 2017-05-15T23:53:46.736+03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(serviceName = "OrderShipmentServiceService", portName = "OrderShipmentServicePort", targetNamespace = "http://server.order.idu0080.ttu/", wsdlLocation = "file:/C:/Users/Tony Bigwell/workspace/ProductServer/WebContent/order_shipments_1.wsdl", endpointInterface = "ttu.idu0080.order.server.OrderShipmentService")

public class OrderShipmentServiceImpl implements OrderShipmentService {

	private static final Logger LOG = Logger.getLogger(OrderShipmentServiceImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see ttu.idu0080.order.server.OrderShipmentService#
	 * getOrderShipmentsByOrderIdRyhmName(int orderId, java.lang.String
	 * ryhmName)*
	 */
	public java.util.List<ttu.idu0080.order.server.OrderShipment> getOrderShipmentsByOrderIdRyhmName(int orderId,
			java.lang.String ryhmName) {
		LOG.info("Executing operation getOrderShipmentsByOrderIdRyhmName");
		System.out.println(orderId);
		System.out.println(ryhmName);
		try {
			Class.forName("org.postgresql.Driver");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Connection connection = null;
		try {
			connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/myDB", "postgres", "");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if (connection != null) {
			System.out.println("You made it, take control your database now!");
			try {
				PreparedStatement st = connection.prepareStatement(
						"SELECT * FROM order_shipment WHERE order_fk="+orderId+" AND ryhm_name='"+ryhmName+"'");
				ResultSet rs = st.executeQuery();
				java.util.List<ttu.idu0080.order.server.OrderShipment> _return = new java.util.ArrayList<ttu.idu0080.order.server.OrderShipment>();
				while (rs.next()) {
					try {
			            ttu.idu0080.order.server.OrderShipment _returnVal1 = new ttu.idu0080.order.server.OrderShipment();
			            _returnVal1.setApproxDeliveryDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar(rs.getString(6)));
			            _returnVal1.setCourierName(rs.getString(4));
			            _returnVal1.setOrder(rs.getInt(2));
			            _returnVal1.setOrderShipment(rs.getInt(1));
			            _returnVal1.setRyhmName(rs.getString(8));
			            _returnVal1.setShippingPrice(rs.getDouble(5));
			            _returnVal1.setTrackingNumber(rs.getString(3));
			            _return.add(_returnVal1);

					} catch (java.lang.Exception ex) {
						ex.printStackTrace();
						throw new RuntimeException(ex);
					}
				}
				return _return;

			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			System.out.println("Failed to make connection!");
		}
		try {
			connection.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * ttu.idu0080.order.server.OrderShipmentService#insertOrderShipment(int
	 * orderId, java.lang.String ryhmName, java.lang.String trackingNumber,
	 * java.lang.String courierName, javax.xml.datatype.XMLGregorianCalendar
	 * approxDeliveryDate, double shippingPrice)*
	 */
	public int insertOrderShipment(int orderId, java.lang.String ryhmName, java.lang.String trackingNumber,
			java.lang.String courierName, javax.xml.datatype.XMLGregorianCalendar approxDeliveryDate,
			double shippingPrice) {
		LOG.info("Executing operation insertOrderShipment");

		try {
			Class.forName("org.postgresql.Driver");
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		Connection connection = null;
		try {
			connection = DriverManager.getConnection("jdbc:postgresql://localhost:5432/myDB", "postgres", "");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		if (connection != null) {
			System.out.println("You made it, take control your database now!");
			try {
				PreparedStatement st = connection.prepareStatement(
						"INSERT INTO order_shipment(order_fk, tracking_number, courier_name, shipping_price, approx_delivery_date, created, ryhm_name) VALUES ("
				+ Integer.toString(orderId) + ",'"+trackingNumber+"','"+courierName+"',"+Double.toString(shippingPrice)+",TIMESTAMP '"+approxDeliveryDate.toGregorianCalendar().getTime()+"',NOW(),'"+ryhmName+"')");
				//System.out.println(st);
				ResultSet rs = st.executeQuery();

			} catch (SQLException e) {
				// TODO Auto-generated catch block
				//System.out.println(e);
				//e.printStackTrace();
			}
		} else {
			System.out.println("Failed to make connection!");
		}
		try {
			connection.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return 200;
	}

}
