
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ttu.idu0080.order.server;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T18:30:30.988+03:00
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "OrderServiceService",
                      portName = "OrderServicePort",
                      targetNamespace = "http://server.order.idu0080.ttu/",
                      wsdlLocation = "http://localhost:8080/OrderServer/services/OrderServicePort?wsdl",
                      endpointInterface = "ttu.idu0080.order.server.OrderService")
                      
public class OrderServiceImpl implements OrderService {

    private static final Logger LOG = Logger.getLogger(OrderServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerId(int customerId)*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerId(int customerId) { 
        LOG.info("Executing operation getOrdersByCustomerId");
        System.out.println(customerId);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-129851425);
            _returnVal1Customer.setFirstName("FirstName-1961254318");
            _returnVal1Customer.setLastName("LastName-641946393");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-28057649);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(320526642);
            _returnVal1OrderProductsVal1.setPrice(0.81392384f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.009250939f);
            _returnVal1OrderProductsVal1.setProductCount(1280290837);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1566543837");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.7323788f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1242619801);
            _returnVal1Seller.setName("Name1010469480");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(1855784154);
            _returnVal1ShippingAddress.setCountry("Country-1263367762");
            _returnVal1ShippingAddress.setCounty("County-953662697");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1268894217");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1418473287");
            _returnVal1ShippingAddress.setZipcode("Zipcode-2020777770");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getAllOrders()*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getAllOrders() { 
        LOG.info("Executing operation getAllOrders");
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(-781431202);
            _returnVal1Customer.setFirstName("FirstName1030366314");
            _returnVal1Customer.setLastName("LastName1982757039");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(1993433784);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1393721567);
            _returnVal1OrderProductsVal1.setPrice(0.7649607f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.022768974f);
            _returnVal1OrderProductsVal1.setProductCount(-1393094821);
            _returnVal1OrderProductsVal1.setProductName("ProductName-731948242");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.8495402f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(836175130);
            _returnVal1Seller.setName("Name-1550700109");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(1121027575);
            _returnVal1ShippingAddress.setCountry("Country-923507771");
            _returnVal1ShippingAddress.setCounty("County-36938845");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1473299934");
            _returnVal1ShippingAddress.setTownVillage("TownVillage1281618994");
            _returnVal1ShippingAddress.setZipcode("Zipcode2069805008");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByOrderId(int orderId)*
     */
    public ttu.idu0080.order.server.Order getOrdersByOrderId(int orderId) { 
        LOG.info("Executing operation getOrdersByOrderId");
        System.out.println(orderId);
        try {
            ttu.idu0080.order.server.Order _return = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnCustomer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnCustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            ttu.idu0080.order.server.Address _returnCustomerAddressesVal1 = new ttu.idu0080.order.server.Address();
            _returnCustomerAddressesVal1.setAddress(6489045);
            _returnCustomerAddressesVal1.setCountry("Country-1102234302");
            _returnCustomerAddressesVal1.setCounty("County110326933");
            _returnCustomerAddressesVal1.setStreetAddress("StreetAddress1164006301");
            _returnCustomerAddressesVal1.setTownVillage("TownVillage937060109");
            _returnCustomerAddressesVal1.setZipcode("Zipcode1278384865");
            _returnCustomerAddresses.add(_returnCustomerAddressesVal1);
            _returnCustomer.getAddresses().addAll(_returnCustomerAddresses);
            _returnCustomer.setCustomer(44525130);
            _returnCustomer.setFirstName("FirstName-1972821083");
            _returnCustomer.setLastName("LastName-2040287632");
            _return.setCustomer(_returnCustomer);
            _return.setOrderId(263622988);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnOrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnOrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnOrderProductsVal1.setOrderProduct(1552188642);
            _returnOrderProductsVal1.setPrice(0.04918188f);
            _returnOrderProductsVal1.setPriceTotal(0.054915488f);
            _returnOrderProductsVal1.setProductCount(419053776);
            _returnOrderProductsVal1.setProductName("ProductName1783365512");
            _returnOrderProducts.add(_returnOrderProductsVal1);
            _return.getOrderProducts().addAll(_returnOrderProducts);
            _return.setPriceTotal(0.118258715f);
            ttu.idu0080.order.server.Seller _returnSeller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnSellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            ttu.idu0080.order.server.EntAddress _returnSellerAddressesVal1 = new ttu.idu0080.order.server.EntAddress();
            _returnSellerAddressesVal1.setAddress(-1284258609);
            _returnSellerAddressesVal1.setCountry("Country263185277");
            _returnSellerAddressesVal1.setCounty("County-1736945799");
            _returnSellerAddressesVal1.setStreetAddress("StreetAddress-1913771285");
            _returnSellerAddressesVal1.setTownVillage("TownVillage-2124041505");
            _returnSellerAddressesVal1.setZipcode("Zipcode-331924179");
            _returnSellerAddresses.add(_returnSellerAddressesVal1);
            _returnSeller.getAddresses().addAll(_returnSellerAddresses);
            _returnSeller.setEnterprise(-2092138061);
            _returnSeller.setName("Name-2136055685");
            _return.setSeller(_returnSeller);
            ttu.idu0080.order.server.Address _returnShippingAddress = new ttu.idu0080.order.server.Address();
            _returnShippingAddress.setAddress(-1543863383);
            _returnShippingAddress.setCountry("Country-322795580");
            _returnShippingAddress.setCounty("County1250027500");
            _returnShippingAddress.setStreetAddress("StreetAddress-651359962");
            _returnShippingAddress.setTownVillage("TownVillage1865504342");
            _returnShippingAddress.setZipcode("Zipcode-936943688");
            _return.setShippingAddress(_returnShippingAddress);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByShippingAddress(java.lang.String country, java.lang.String county)*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByShippingAddress(java.lang.String country, java.lang.String county) { 
        LOG.info("Executing operation getOrdersByShippingAddress");
        System.out.println(country);
        System.out.println(county);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(1785423045);
            _returnVal1Customer.setFirstName("FirstName-1174050748");
            _returnVal1Customer.setLastName("LastName-219747573");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-1741458221);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(-2054895809);
            _returnVal1OrderProductsVal1.setPrice(0.042663157f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.10822564f);
            _returnVal1OrderProductsVal1.setProductCount(1419051831);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1646794387");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.15726054f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(1142772948);
            _returnVal1Seller.setName("Name-370976605");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(1577617003);
            _returnVal1ShippingAddress.setCountry("Country1951005914");
            _returnVal1ShippingAddress.setCounty("County1816341658");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress1850993139");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1988953202");
            _returnVal1ShippingAddress.setZipcode("Zipcode-373137004");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ttu.idu0080.order.server.OrderService#getOrdersByCustomerLastName(java.lang.String lastName)*
     */
    public java.util.List<ttu.idu0080.order.server.Order> getOrdersByCustomerLastName(java.lang.String lastName) { 
        LOG.info("Executing operation getOrdersByCustomerLastName");
        System.out.println(lastName);
        try {
            java.util.List<ttu.idu0080.order.server.Order> _return = new java.util.ArrayList<ttu.idu0080.order.server.Order>();
            ttu.idu0080.order.server.Order _returnVal1 = new ttu.idu0080.order.server.Order();
            ttu.idu0080.order.server.Customer _returnVal1Customer = new ttu.idu0080.order.server.Customer();
            java.util.List<ttu.idu0080.order.server.Address> _returnVal1CustomerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.Address>();
            _returnVal1Customer.getAddresses().addAll(_returnVal1CustomerAddresses);
            _returnVal1Customer.setCustomer(1838242614);
            _returnVal1Customer.setFirstName("FirstName-479413011");
            _returnVal1Customer.setLastName("LastName953772252");
            _returnVal1.setCustomer(_returnVal1Customer);
            _returnVal1.setOrderId(-4792079);
            java.util.List<ttu.idu0080.order.server.OrderProduct> _returnVal1OrderProducts = new java.util.ArrayList<ttu.idu0080.order.server.OrderProduct>();
            ttu.idu0080.order.server.OrderProduct _returnVal1OrderProductsVal1 = new ttu.idu0080.order.server.OrderProduct();
            _returnVal1OrderProductsVal1.setOrderProduct(1552071022);
            _returnVal1OrderProductsVal1.setPrice(0.5695368f);
            _returnVal1OrderProductsVal1.setPriceTotal(0.6283858f);
            _returnVal1OrderProductsVal1.setProductCount(-1209333956);
            _returnVal1OrderProductsVal1.setProductName("ProductName-1438249157");
            _returnVal1OrderProducts.add(_returnVal1OrderProductsVal1);
            _returnVal1.getOrderProducts().addAll(_returnVal1OrderProducts);
            _returnVal1.setPriceTotal(0.83670396f);
            ttu.idu0080.order.server.Seller _returnVal1Seller = new ttu.idu0080.order.server.Seller();
            java.util.List<ttu.idu0080.order.server.EntAddress> _returnVal1SellerAddresses = new java.util.ArrayList<ttu.idu0080.order.server.EntAddress>();
            _returnVal1Seller.getAddresses().addAll(_returnVal1SellerAddresses);
            _returnVal1Seller.setEnterprise(675264244);
            _returnVal1Seller.setName("Name181651049");
            _returnVal1.setSeller(_returnVal1Seller);
            ttu.idu0080.order.server.Address _returnVal1ShippingAddress = new ttu.idu0080.order.server.Address();
            _returnVal1ShippingAddress.setAddress(1403570656);
            _returnVal1ShippingAddress.setCountry("Country762063579");
            _returnVal1ShippingAddress.setCounty("County683462344");
            _returnVal1ShippingAddress.setStreetAddress("StreetAddress-1481014732");
            _returnVal1ShippingAddress.setTownVillage("TownVillage-1347518658");
            _returnVal1ShippingAddress.setZipcode("Zipcode877577139");
            _returnVal1.setShippingAddress(_returnVal1ShippingAddress);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
