package ttu.idu0080.order.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-05-22T23:16:48.608+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://server.order.idu0080.ttu/", name = "OrderShipmentService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrderShipmentService {

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/OrderShipmentService/getOrderShipmentsByOrderIdRyhmNameRequest", output = "http://server.order.idu0080.ttu/OrderShipmentService/getOrderShipmentsByOrderIdRyhmNameResponse")
    @RequestWrapper(localName = "getOrderShipmentsByOrderIdRyhmName", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetOrderShipmentsByOrderIdRyhmName")
    @ResponseWrapper(localName = "getOrderShipmentsByOrderIdRyhmNameResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.GetOrderShipmentsByOrderIdRyhmNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ttu.idu0080.order.server.OrderShipment> getOrderShipmentsByOrderIdRyhmName(
        @WebParam(name = "order_id", targetNamespace = "")
        int orderId,
        @WebParam(name = "ryhm_name", targetNamespace = "")
        java.lang.String ryhmName
    );

    @WebMethod
    @Action(input = "http://server.order.idu0080.ttu/OrderShipmentService/insertOrderShipmentRequest", output = "http://server.order.idu0080.ttu/OrderShipmentService/insertOrderShipmentResponse")
    @RequestWrapper(localName = "insertOrderShipment", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.InsertOrderShipment")
    @ResponseWrapper(localName = "insertOrderShipmentResponse", targetNamespace = "http://server.order.idu0080.ttu/", className = "ttu.idu0080.order.server.InsertOrderShipmentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int insertOrderShipment(
        @WebParam(name = "order_id", targetNamespace = "")
        int orderId,
        @WebParam(name = "ryhm_name", targetNamespace = "")
        java.lang.String ryhmName,
        @WebParam(name = "tracking_number", targetNamespace = "")
        java.lang.String trackingNumber,
        @WebParam(name = "courier_name", targetNamespace = "")
        java.lang.String courierName,
        @WebParam(name = "approx_delivery_date", targetNamespace = "")
        javax.xml.datatype.XMLGregorianCalendar approxDeliveryDate,
        @WebParam(name = "shipping_price", targetNamespace = "")
        double shippingPrice
    );
}
