package ttu.idu0080.order.transport;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-05-20T20:31:47.145+03:00
 * Generated source version: 3.1.9
 * 
 */
@WebServiceClient(name = "Transport", 
                  wsdlLocation = "file:/C:/Users/Smarta/Documents/veebiteenused1/IDU0080-04/OrderTeenus/WebContent/wsdl/transport.wsdl",
                  targetNamespace = "http://www.example.org/transport/") 
public class Transport_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/transport/", "Transport");
    public final static QName TransportSOAP = new QName("http://www.example.org/transport/", "transportSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/Smarta/Documents/veebiteenused1/IDU0080-04/OrderTeenus/WebContent/wsdl/transport.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Transport_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/Smarta/Documents/veebiteenused1/IDU0080-04/OrderTeenus/WebContent/wsdl/transport.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Transport_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Transport_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Transport_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Transport_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Transport_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Transport_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TransportService
     */
    @WebEndpoint(name = "transportSOAP")
    public TransportService getTransportSOAP() {
        return super.getPort(TransportSOAP, TransportService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransportService
     */
    @WebEndpoint(name = "transportSOAP")
    public TransportService getTransportSOAP(WebServiceFeature... features) {
        return super.getPort(TransportSOAP, TransportService.class, features);
    }

}
