
package ttu.idu0080.order.transport;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-05-20T20:31:47.018+03:00
 * Generated source version: 3.1.9
 * 
 */
public final class TransportService_TransportSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.example.org/transport/", "Transport");

    private TransportService_TransportSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Transport_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Transport_Service ss = new Transport_Service(wsdlURL, SERVICE_NAME);
        TransportService port = ss.getTransportSOAP();  
        
        {
        System.out.println("Invoking transportType...");
        java.lang.String _transportType_pakkumiseId = "_transportType_pakkumiseId1054538042";
        port.transportType(_transportType_pakkumiseId);


        }
        {
        System.out.println("Invoking transport...");
        ttu.idu0080.order.transport.Transport _transport_parameters = new ttu.idu0080.order.transport.Transport();
        _transport_parameters.setTrackingId("TrackingId-500735498");
        ttu.idu0080.order.transport.TransportResponse _transport__return = port.transport(_transport_parameters);
        System.out.println("transport.result=" + _transport__return);


        }

        System.exit(0);
    }

}
