
package ttu.idu0080.order.teenus;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.9
 * 2017-05-18T12:32:23.372+03:00
 * Generated source version: 3.1.9
 * 
 */
 
public class CourierTeenusServer{

    protected CourierTeenusServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ttu.idu0080.order.teenus.OrderTeenus();
        String address = "http://localhost:9090/OrderTeenusPort";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new CourierTeenusServer();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
 
 